### ISSUE TITLE
Fetch failed for DB endpoint

### ISSUE THREAD

**Issue by apekearo** [shellyln/kanban-board-app#6]
My issue is that I unable to figure out how to keep the Kanban persistent.  I have an ibm DB like you mention in the README.
The actions taken are not persistent across each users device.
This is my current settings.  I've tried with and without quotes, but the quotes keep being taken away.  I've tried with and without the https:// before the endpoint, and without it says it is successful, but I'm unable to see any data being sent to my database.  Any advice would be appreciated. Thank you

# App settings

remote:
  endpointUrl: 0b42ab46-7924-479c-89db-e26d674e13cb-bluemix.cloudantnosqldb.appdomain.cloud
  user: a****@gmail.com
  password: h****
display:
  autoUpdate: true
  autoUpdateInterval: 24200
  goAround: false

**Comment by shellyln** [comment]
1. Where do you host the `kanban-board-app`?  
    Is it on `https://shellyln.github.io/knbn/`, or do you host it yourself?  
    If you're doing it yourself, which version (commit) are you using?
1. Do you see any errors in your browser's developer console?

**Comment by apekearo** [comment]
Thank you for getting back to me!
I forked the repo from yours this week.  I took your latest version.

_Merge pull request shellyln#5 from shellyln/update-deps-20201229a
Update deps 20201229a
Update dependencies
Update CI configurations
Update service worker_

Here's my forked repo on an new branch: https://github.com/apekearo/kanban-board-app/tree/SkoolKanBan

I then had the repo hosted from github pages.  I had some issues with the entry point going to the readme, so i just add on to the url.  https://apekearo.github.io/kanban-board-app/build/#/kanban
When clicking around, it creates a tag at the end of the url /kanban/0376b222-41a8-479d-af35-8539ffdbc813
Which says to me there is some unique ID being created for the user instance.

There is no error in the console when i save the settings with the DB info I showed in the previous post.  But this error pops up when clicking around the app.
 
_Error in event handler: TypeError: Cannot read property 'id' of undefined
    at rerunParse (chrome-extension://lghjfnfolmcikomdjmoiemllfnlmmoko/js/main.js:1731:23)
    at onRequest (chrome-extension://lghjfnfolmcikomdjmoiemllfnlmmoko/js/main.js:1111:9)_

Running my DB endpoint works in Postman as long as I put the https:// infront of the endpoint get call, but it produces this error in your prompt "Failed to connect to the remote DB: Failed to fetch".  So I am not putting the https in my saved settings.

Thank you for replying and for any advice you give.  I really like the structure you followed to make this app, and I look forward to adding some features for home schooling kids.  My good friend says she can't handle juggling work and keeping her kids on path while home schooling.  So I figured a Kanban would be helpful for her and her daughter to stay on the same page from their cell phones.  Thank you again!

**Comment by shellyln** [comment]
Hi @apekearo !

Settings format is following:
```yaml
# App settings

remote:
  # `External Endpoint (preferred)` of `Non-partitioned` Cloudant Db
  # If you use `External Endpoint` URL(`https://*-bluemix.cloudantnosqldb.appdomain.cloud`) and use Cloudant Dashboard GUI,
  # connenction is failed until removing cookies.
  endpointUrl: https://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-bluemix.cloudantnosqldb.appdomain.cloud
  # API Key
  user: apikey-xxxxxxxxxxxxxxxxxxxxxxxx
  # Password of API Key
  password: your-apikey-password
display:
  autoUpdate: false
  autoUpdateInterval: 100000
  goAround: false
```

I've deployed latest version (`3248323`) to `https://shellyln.github.io/knbn-stg/`, and it works on my latest Chrome browser.
Please check it on the original latest and your branch.
